# Databricks notebook source
main_metadata   = {'ASD12' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD12a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD12b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD13' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD13a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD13b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'ref_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD16' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'open_pat_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD16a': {'SOURCE_TABLE'  : 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN'    : 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'open_13_pat_count',
                              'FILTERCOLUMN'  : '',
                              'FILTERVALUE'   : ''},
                   'ASD16b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'open_pat_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD16c': {'SOURCE_TABLE'  : 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN'    : 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'open_13_pat_count',
                              'FILTERCOLUMN'  : '',
                              'FILTERVALUE'   : ''},
                   'ASD16d': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'open_pat_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD16e': {'SOURCE_TABLE'  : 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN'    : 'ReferralRequestReceivedDate',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'open_13_pat_count',
                              'FILTERCOLUMN'  : '',
                              'FILTERVALUE'   : ''},
                   'ASD20' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'contacts_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD20a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'contacts_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD20b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'contacts_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD21' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'ref_diag_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD21a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'ref_diag_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD21b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'CareContDate',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': 'ref_diag_count',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD23' : {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other F"'},
                   'ASD23a': {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other F"'},
                   'ASD23b': {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other F"'},
                   'ASD24' : {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other"'},
                   'ASD24a': {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other"'},
                   'ASD24b': {'SOURCE_TABLE': 'Autism_Diagnoses',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': 'ServDischDate',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'diag_count',
                              'FILTERCOLUMN': 'diag',
                              'FILTERVALUE': '"Other"'}
                  }

# COMMAND ----------

#This only lists the count metrics, not the proportions
waits_metadata =  {'ASD18' : {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'Less than 13 weeks'},
                   'ASD18a': {'SOURCE_TABLE'  : 'WaitTimes',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN'    : '',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'not',
                              'FILTERCOLUMN'  : 'WaitLength',
                              'FILTERVALUE'   : 'No Contact'},
                   'ASD18b': {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'No Contact'},
                   'ASD18c': {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'Less than 13 weeks'},
                   'ASD18d': {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'Less than 13 weeks'},
                   'ASD18e': {'SOURCE_TABLE'  : 'WaitTimes',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN'    : '',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'not',
                              'FILTERCOLUMN'  : 'WaitLength',
                              'FILTERVALUE'   : 'No Contact'},
                   'ASD18f': {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'No Contact'},
                   'ASD18g': {'SOURCE_TABLE'  : 'WaitTimes',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN'    : '',
                              'COUNTCOLUMN'   : 'Person_ID',
                              'METRIC_TYPE'   : 'not',
                              'FILTERCOLUMN'  : 'WaitLength',
                              'FILTERVALUE'   : 'No Contact'},
                   'ASD18h': {'SOURCE_TABLE': 'WaitTimes',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': 'WaitLength',
                              'FILTERVALUE': 'No Contact'}
                  }

# COMMAND ----------

#This only lists the proportion metrics, with the required numerator and denominator metrics
props_metadata =  {'ASD19' : {'NUMERATOR': 'ASD18',
                              'DENOMINATOR': 'ASD16a'},
                   'ASD19a': {'NUMERATOR': 'ASD18a',
                              'DENOMINATOR': 'ASD16a'},
                   'ASD19b': {'NUMERATOR': 'ASD18b',
                              'DENOMINATOR': 'ASD16a'},
                   'ASD19c': {'NUMERATOR': 'ASD18c',
                              'DENOMINATOR': 'ASD16c'},
                   'ASD19d': {'NUMERATOR': 'ASD18d',
                              'DENOMINATOR': 'ASD16e'},
                   'ASD19e': {'NUMERATOR': 'ASD18e',
                              'DENOMINATOR': 'ASD16c'},
                   'ASD19f': {'NUMERATOR': 'ASD18f',
                              'DENOMINATOR': 'ASD16c'},
                   'ASD19g': {'NUMERATOR': 'ASD18g',
                              'DENOMINATOR': 'ASD16e'},
                   'ASD19h': {'NUMERATOR': 'ASD18h',
                              'DENOMINATOR': 'ASD16e'}
                  }

# COMMAND ----------

#This only lists the count metrics (ASD11, ASD14 and ASD17)
dq_metadata =    {'ASD11' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'open_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD11a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'open_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD11b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'open_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD14' : {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'last_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD14a': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'last_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD14b': {'SOURCE_TABLE': 'Autism_12m_Referrals',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'UniqServReqID',
                              'METRIC_TYPE': 'last_refs',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD17' : {'SOURCE_TABLE': 'Autism_12m_Referrals_ASD17',
                              'AGEGROUPHIGHER': '',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD17a': {'SOURCE_TABLE': 'Autism_12m_Referrals_ASD17',
                              'AGEGROUPHIGHER': 'Under 18',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''},
                   'ASD17b': {'SOURCE_TABLE': 'Autism_12m_Referrals_ASD17',
                              'AGEGROUPHIGHER': '18 and over',
                              'DATECOLUMN': '',
                              'COUNTCOLUMN': 'Person_ID',
                              'METRIC_TYPE': '',
                              'FILTERCOLUMN': '',
                              'FILTERVALUE': ''}
                  }

# COMMAND ----------

#This only lists all non-dq and non-waiting time metrics
output_metadata = {'ASD11' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD11a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD11b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD14' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD14a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD14b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD17' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD17a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD17b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD12' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD12a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD12b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD13' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD13a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD13b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16c': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16d': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD16e': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD20' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD20a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD20b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD21' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD21a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD21b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD23' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD23a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD23b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD24' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD24a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD24b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18' : {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18a': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18b': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18c': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18d': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18e': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18f': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18g': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD18h': {'METRIC_TYPE': 'COUNT',
                              'NUMERATOR': '',
                              'DENOMINATOR': ''},
                   'ASD19' : {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18',
                              'DENOMINATOR': ''},
                   'ASD19a': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18a',
                              'DENOMINATOR': ''},
                   'ASD19b': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18b',
                              'DENOMINATOR': ''},
                   'ASD19c': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18c',
                              'DENOMINATOR': ''},
                   'ASD19d': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18d',
                              'DENOMINATOR': ''},
                   'ASD19e': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18e',
                              'DENOMINATOR': ''},
                   'ASD19f': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18f',
                              'DENOMINATOR': ''},
                   'ASD19g': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18g',
                              'DENOMINATOR': ''},
                   'ASD19h': {'METRIC_TYPE': 'RATE',
                              'NUMERATOR': 'ASD18h',
                              'DENOMINATOR': ''}
                  }

# COMMAND ----------

breakdowns_metadata = { 'England' :{'name':'England',
                                   'column':'"England"'},
                       'AGE_LL'  :{'name':'Age Group',
                                   'column':'Age_Group'},
                       'ETH_LL'  :{'name':'Ethnicity',
                                   'column':'LowerEthnicity'},
                       'GENDER'  :{'name':'Gender',
                                   'column':'Der_Gender'}
                       }

# COMMAND ----------

geog_breakdown_metadata = {'CCG'     : {'name':'CCG or Sub ICB Location - GP Practice or Residence',
                                        'codecol':'CCGCODE',
                                        'namecol':'CCGNAME',
                                        'spellscol':'CCGCODE',
                                        'demogsuffix':''},
                           'Provider': {'name':'Provider',
                                        'codecol':'OrgIDProv',
                                        'namecol':'Name',
                                        'spellscol':'OrgIDProv',
                                        'demogsuffix':'_Prov'},
                           'STP'     : {'name':'STP or ICB - GP Practice or Residence',
                                        'codecol':'STPCode',
                                        'namecol':'STPName',
                                        'spellscol':'STPCode',
                                        'demogsuffix':''},
                           'REGION'  : {'name':'Commissioning Region - GP Practice or Residence',
                                        'codecol':'RegionCode',
                                        'namecol':'RegionName',
                                        'spellscol':'RegionCode',
                                        'demogsuffix':''}
                          }